### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by AdamYLiang** [kamanfi/ThisCord#1]
- [x] Try to keep the total days to completion at 10 days max
- [x] Break up search and add friends into 2 separate MVP, perhaps make one of them a bonus MVP.

Let me know if you have any questions or want more details!

**Comment by AdamYLiang** [comment]
Nice changes to MVP list, I have one more for you and then it looks good. 

- [ ] Separate chat and private chat(DMs) into two separate MVPS.
- [ ] Total of 7 MVPs with optional bonus.

**Comment by kamanfi** [comment]
Thanks for the tips, the suggested changed have been added

**Comment by AdamYLiang** [comment]
Nice work! Just a few more small changes  and it's good to go.
- [ ] Add some bullet points for the chat features (CRUD actions for messages)
- [ ] Remove `README` from `Private Chat` MVP
