### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by AdamYLiang** [kamanfi/ThisCord#2]
**All tables** 
- [x] `id` column should exist
- [x] `created_at/updated_at` columns should exist from timestamps

**Users Table**
- [x]  Password digest should not be unique 
- [x] Index on `session token`
- [x] Index on `email`
Consider renaming `username_identifier` since it can be confused with the username. Perhaps `discord_id` or `account_id`. 

**Servers** 
- [x] Index on `server_name` 

**Text Channels** 
- [x] Needs a column for name of channel

**Voice Channels** 
- [x] Needs a column for name of channel 
Make this a bonus feature

**Messages** 
- [x] Index on `author_id`
- [x] `author_id` should be a foreign key

Let me know if you have any questions or want to talk about any of these!

**Comment by kamanfi** [comment]
I have made the recommended suggestions, please review. 
I am thinking of merging the text and voice channel  table into one table. I will then add a col that will determine if each row is a voice channel or a text channel . please let me know if this will be a good idea.

**Comment by AdamYLiang** [comment]
Changes look good! Just one small tweak:
-[ ] **Text Channel** / **Voice Channel** - Shorten `channel_name` to just `name` if you find it more convenient 

As for the voice channel, I feel that keeping them separate for now will be better since Discord has a pretty hard distinction between the two (text channel settings are very different from voice channel settings). Furthermore since voice is a bonus MVP, it would be a bit easier to not worry about them while doing the original 7 MVPs.
